spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e-waste_management_system-Recycling_Center?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

server:
  port : 8083